### ISSUE TITLE
The clickable area for the "Next Button" needs to be made bigger.

### ISSUE THREAD

**Issue by sonagrigoryan** [ProjectTrace/Trace#45]
It is very hard to click on this button. If not too precisely touched, it does not respond. ("Next button shown on the page below".
![18_aa76819df9c84c399dfe906a77c3afd5b4a145de_o](https://cloud.githubusercontent.com/assets/3656013/5890382/bf207c3a-a40c-11e4-844f-2027b95bc304.jpg)

**Comment by iam-ethan-huang** [comment]
New UI and no this problem anymore
